packages/next-templates/src/app/page.tsx
packages/next-templates/src/app/styling/component-styles/header.css

Header styling

---

packages/next-templates/src/app/ryan/form/page.tsx
packages/next-templates/src/components/ExampleFooter/ExampleFooter.tsx
packages/next-templates/src/components/ExampleFooter/ExampleFooterFocus/ExampleFooterFocus.tsx
packages/next-templates/src/components/ExampleFooter/footer.css

**Footer Styling**
Added a margin-block and margin-inline for perfect alignment with the logo and also not touching the logo when made smaller but keeping space between them.
**Header**
I removed the header because it was ruining the responsive footer because of the logo not being correct, so i removed it and put it back again

Example footer styling

---

package.json
packages/next-templates/src/app/styling/assets/x-bold.svg
packages/next-templates/src/components/ExampleHeader/ExampleHeader.tsx
packages/next-templates/src/components/ExampleHeader/header.css
packages/next-templates/src/components/ExampleHeader/header.scss
packages/next-templates/src/components/ExampleNavigation/Navigation.css
packages/next-templates/src/components/PopOver/PopOverButton.tsx
packages/next-templates/src/components/PopOver/PopOverDialog.tsx
pnpm-lock.yaml

responsive pop over menu voledig gestyled

Header styling responsive

---

packages/next-templates/src/app/globals.css
packages/next-templates/src/app/ryan/form/page.tsx

- added a custom classname for a  TextArea in the form page that needs to be bigger than usual because of character length 
- added className to the designated TextArea

Textarea rows

---

.github/workflows/check-draft.yml
packages/next-templates/src/app/styling/assets/x-bold.svg
packages/next-templates/src/components/ExampleHeader/ExampleHeader.tsx
packages/next-templates/src/components/ExampleHeader/header.css
packages/next-templates/src/components/PopOver/PopOverButton.tsx

het pop over menu ziet er nu helemaal precies uit zoals het figma dat Jeffrey had gemaakt.
En bij de popover button dat een custom component is. heb ik een onclick event gemaakt die er voor zorgt dat als het pop over menu opent, de focus alleen in de menu blijft en niet buiten het menu door gaat.

Pop over menu

---

packages/next-templates/src/app/detail/page.tsx

- updated the href in the "melding doen" button

✨ melding doen button now works and goes to the form-page

---

packages/next-templates/src/app/form/page.tsx

[Changes]
- Fix typos in FormLabels 'E-mailadres' and 'Telefoonnummer'

Fix typos in FormLabels

---

packages/next-templates/src/app/styling/css/wrong-form-socks.css
packages/next-templates/src/app/wrong-forms/page.tsx
packages/next-templates/src/components/ExampleHeader/ExampleHeaderFunnel/exampleheaderfunnel.css

forms met fouten die voor Robbert en Hidde bingo.

Foute forms

---

packages/next-templates/src/app/form/page.tsx
packages/next-templates/src/app/globals.css
packages/next-templates/src/app/styling/css/form-page.css

- renamed className for better understanding 
- changed rabbit design token to snail
- removed unused CSS

Bijlage space update

---

packages/next-templates/src/app/form/page.tsx
packages/next-templates/src/app/styling/css/form-page.css

- the border-bottom-width is now 1px instead of 3px

💄 added classname for bottom-border-width

---

packages/next-templates/src/app/globals.css

- added padding to ul to match figma design

💄 added padding to ul to match the figma

---

packages/next-templates/src/components/ExampleHeader/header.css

Header spacing

---

packages/next-templates/src/app/vng-form/form/page.tsx

**[Changes]**
- Created the form for Model aanwijzingsbesluit

:sparkles: Added aanwijsbesluit-form

---

packages/next-templates/src/app/wmebv/ingelogd/stap1/page.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap2/page.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap3/page.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap4/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap1/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap3/page.tsx
packages/next-templates/src/components/ExampleHeader/wmebv/ExampleHeaderFunnelWmebv.tsx

- Added stap 1 t/m 4 page
- added Funnel Header wmebv
- removed unused imports
- removed navigation in Header
- removed paragraphs and divs in ButtonGroup

Ingelogd pagina's

---

packages/next-templates/src/app/globals.css
packages/next-templates/src/app/styling/css/wmebv.css
packages/next-templates/src/app/wmebv/Inloggen/page.tsx
packages/next-templates/src/app/wmebv/Intro/page.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap1/page.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap2/page.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap3/page.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap4/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap1/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap2/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap3/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap4/page.tsx

- Compared the Form to the Figma and resolved the differences between them. 
- Edited styling for textbox's to match the Figma
- Merged Branch #306 into this Branch to resolve build errors

wmebv looking for differences 

---

packages/next-templates/src/utils/validation.ts

fix: validation message of e-mailadres

---

packages/next-templates/src/utils/validation.ts

- Typo's fixed in form validation messages
~- ik wacht nog op antwoord van Jeffrey dus merge nog niet~

🎨 fixed validation message typo's

---

packages/next-templates/src/app/wmebv/ingelogd/stap4/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap4/page.tsx

- "Uw" toegevoegd aan de succes alert

🎨 added "Uw" to the alert

---

packages/next-templates/src/app/globals.css
packages/next-templates/src/app/wmebv/ingelogd/stap1/page.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap2/page.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap3/home.tsx
packages/next-templates/src/app/wmebv/ingelogd/stap3/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap1/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap2/page.tsx
packages/next-templates/src/app/wmebv/niet-ingelogd/stap3/page.tsx

[Before](https://cdn.discordapp.com/attachments/1077934662879563928/1174363681677647982/Screenshot_2023-11-15_at_16.01.25.png?ex=65675268&is=6554dd68&hm=428438a3a44c91c0ba0f4244b10b443c1c3a8ce4d85ab433e5d47d61e0d95e10&) -> [After](https://cdn.discordapp.com/attachments/1077934662879563928/1174363681878986902/Screenshot_2023-11-15_at_16.01.05.png?ex=65675268&is=6554dd68&hm=0af225f756f86a2417604f5cb219b5bc26f00105c8c05281601760eaed3a738a&)

💄 changed button-font-weight  to link font weight

---

packages/next-templates/src/components/PageHeader.scss

Denhaag header

---

package.json
pnpm-lock.yaml

In de package.json staat nu alleen versie 8 gedefinieerd (let op: hij verwacht versie 8.14.5, ondanks dat dit niet zo specifiek in de package.json staat). De terugkerende problemen rondom pnpm die ik heb ondervonden kosten veel tijd. Het toevoegen van pnpm versie 9  zou het probleem wellicht op kunnen lossen (nog niet getest).

👷 add version 9 pnpm to packag.json

---

packages/next-templates/src/app/klachtenformulier-inloggen/page.tsx
packages/next-templates/src/app/productpagina-klachtenformulier/page.tsx
packages/next-templates/src/app/styling/css/klachtenformulier-inloggen.css

In deze draft PR: de pagina tussen de productpagina het klachtenformulier waar je kunt kiezen om in te loggen (met DigiD of eHerkenning) of door kunt gaan zonder inloggen.

Klachtenformulier inloggen
